name: Deploy monthly or when pushed

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  texlive-ja:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/itk13201/texlive-ja
          flavor: |
            latest=true
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Asia/Tokyo'}}
            type=ref,event=tag
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile
          target: production
